# Molecule managed

FROM --platform=linux/amd64 {{ item.image }}

RUN if [ $(command -v apt-get) ]; then \
        apt-get update && apt-get upgrade -y && \
        apt-get install -y python3 sudo bash ca-certificates net-tools && \
        apt-get clean; \
    elif [ $(command -v dnf) ]; then \
        dnf makecache && dnf --assumeyes install epel-release && \
        dnf --assumeyes install python3 python3-devel python2-dnf bash net-tools && \
        dnf clean all; \
    elif [ $(command -v yum) ]; then \
        yum makecache fast && yum install -y epel-release && yum update -y && \
        yum install -y python3 sudo yum-plugin-ovl bash net-tools  && \
        sed -i 's/plugins=0/plugins=1/g' \
        /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then \
        zypper refresh && zypper update -y && \
        zypper install -y python3 sudo bash python3-xml net-tools && \
        zypper clean -a; \
    elif [ $(command -v apk) ]; then \
        apk update && \
        apk add --no-cache python3 sudo bash ca-certificates; \
    fi

CMD ["sleep", "infinity"]
