name: Tests

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - fix/**

jobs:
  molecule:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run molecule test scenarios
        run: |
          ls -la /var/run/docker.sock
          docker run --rm -v "$PWD":/workspace -w /workspace ghcr.io/ouroborosng/tox-molecule-image:latest tox > ./molecule-logs

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: molecule-logs
          path: |
            .molecule/**/molecule.log
            ~/.cache/molecule
