name: Tests

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - fix/**

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Docker
        run: |
          docker version
          docker info

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run molecule test scenarios
        run: |
          docker run --rm \
            -v "$PWD":/workspace \
            -w /workspace \
            -v /var/run/docker.sock:/var/run/docker.sock \
            ghcr.io/ouroborosng/tox-molecule-image:latest \
            tox > ./molecule-logs

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: molecule-logs
          path: ./molecule-logs
