name: Tests

on:
  push:
    branches: [main, develop]

jobs:
  molecule:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ouroborosng/tox-molecule-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Molecule action
        uses: robertdebock/molecule-action@v6
        with:
          namespace: ouroborosng
          image: tox-molecule-image
          tag: latest
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
        volumes: |
          /var/run/docker.sock:/var/run/docker.sock

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: molecule-logs
          path: |
            .molecule/**/molecule.log
            ~/.cache/molecule
