name: Tests

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - fix/**

jobs:
  molecule:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ouroborosng/tox-molecule-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run molecule test scenarios
        run: tox

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: molecule-logs
          path: |
            .molecule/**/molecule.log
            ~/.cache/molecule
